// Frontend-wide constants. Centralised so a magic number doesn't drift
// between the place that sets it and the place that depends on it.
//
// All durations are milliseconds unless the name says otherwise.

// Heartbeat ping cadence — every 5 s the frontend POSTs /api/system/heartbeat
// so the backend knows the UI is alive and so we can pick up a freshly-issued
// session token. Used by both `main.jsx` (boot loop) and the folder-watcher
// status refresh in `SettingsView.jsx`.
export const HEARTBEAT_INTERVAL_MS = 5000;

// Polling cadence for the library load-status check during boot. Faster than
// the heartbeat because we want the splash to clear the moment the DB lands.
export const LIBRARY_STATUS_INTERVAL_MS = 1000;

// Axios timeout for server-side audio render (/api/audio/render → FFmpeg).
// Large stems / MP3 encodes take real time; 3 minutes is the upper bound
// before we declare the render hung.
export const RENDER_API_TIMEOUT_MS = 180000;

// Delay before we revoke a generated blob: URL after triggering a download.
// Browsers occasionally fetch the same URL twice (preview + download), so
// holding it for a few seconds avoids a "Network error" on the second hit.
export const BLOB_URL_REVOKE_DELAY_MS = 5000;

// Duration for long-form error toasts that the user needs time to read
// (full failure paths in DAW / export). The react-hot-toast default is
// 4 s — bumped to 5 s here so a multi-line message has reading room.
export const TOAST_DURATION_LONG_MS = 5000;

// Axios timeout for the synchronous audio-import endpoint
// (/api/audio/import → full analysis pipeline: copy + decode + BPM +
// key + ANLZ write). Large WAV files (>30 MB) routinely take 30–60 s.
// `0` disables the timeout completely — we trust the backend to either
// finish or return an explicit error.
//
// Kept for backwards-compat: as of the async-import refactor the endpoint
// returns 202-style {task_id} immediately and the frontend polls
// /api/import/tasks, so the timeout is no longer load-bearing.
export const AUDIO_IMPORT_TIMEOUT_MS = 0;

// Poll cadence for /api/import/tasks while one or more uploaded files are
// still being analysed in the background. 1 s feels live without spamming
// the backend; the import_tracker snapshot is cheap (in-memory dict copy).
export const IMPORT_TASK_POLL_INTERVAL_MS = 1000;

// Poll cadence for a running artist-merge job (POST /api/artists/merge/apply →
// job_id, then GET /api/artists/merge/status). Slower than the import poll: a
// merge chunk is 200 rows and the progress numbers only move per chunk.
export const ARTIST_MERGE_POLL_INTERVAL_MS = 1500;

// Consecutive failed status polls tolerated before the dialog stops waiting and
// tells the user it lost the job. A single dropped request is normal while the
// backend holds the DB write lock; five in a row is not.
export const ARTIST_MERGE_MAX_POLL_FAILURES = 5;

// Axios timeout for the long artist-hub mutations (merge apply, merge revert,
// projection sync). `0` disables it: these run under the master.db write lock
// for as long as the library needs, and the default 10 s would abort the request
// while the backend keeps writing — the worst possible outcome.
export const ARTIST_LONG_OP_TIMEOUT_MS = 0;

// Axios timeout for the artist catalogue read (GET /api/artists/{id}/catalogue).
// A cold fetch walks SoundCloud page by page with a spacing sleep between pages, so
// the 10 s default aborts the request while the backend is still legitimately
// working. `0` disables the client-side abort; the backend owns the call budget.
export const ARTIST_CATALOGUE_TIMEOUT_MS = 0;

// Poll cadence for a running artist batch download (POST /api/artists/{id}/
// download-missing → job_id, then GET /api/artists/download/status). The job steps
// once per finished track, so anything faster only re-reads the same numbers.
export const ARTIST_DOWNLOAD_POLL_INTERVAL_MS = 1500;

// Consecutive failed download-status polls tolerated before the view stops waiting
// and says it lost the job. Same reasoning as the merge poll's threshold.
export const ARTIST_DOWNLOAD_MAX_POLL_FAILURES = 5;

// Rows one catalogue bucket renders before the "show more" button. These lists are
// plain DOM (no virtualisation), and a 500-track bucket would jank the panel.
export const ARTIST_CATALOGUE_PAGE_SIZE = 50;

// Minimum tracks a label needs before POST /api/library/smart-playlists writes a
// playlist for it. Artist playlists are NOT generated by that route any more —
// the Artist Hub projection owns the "Artists" folder.
export const SMART_PLAYLIST_LABEL_THRESHOLD = 3;

// Axios timeout for GET /api/artists/discover. One `/related` call per linked
// favourite, spaced by the client's own sleep, so the 10 s default would abort a
// legitimate run. `0` disables the client abort — the backend's CallBudget is the cap.
export const ARTIST_DISCOVER_TIMEOUT_MS = 0;

// Axios timeout for POST /api/artists/sync/run. A pass walks up to 20 favourites
// under one 60-call budget; same reasoning as the discover timeout.
export const ARTIST_SYNC_RUN_TIMEOUT_MS = 0;

// Poll cadence for GET /api/artists/sync/status while the Artists tab is open. The
// answer is a probe sweep plus one sidecar read — cheap, but it only changes when a
// job starts or ends, so a slow poll is enough to keep the idle line honest.
export const ARTIST_SYNC_STATUS_POLL_MS = 20000;

// Suggestions requested from GET /api/artists/discover. Matches the backend's own
// DEFAULT_SUGGESTION_LIMIT — the panel is a shortlist, not a directory.
export const ARTIST_DISCOVER_LIMIT = 25;
